"""Init

Revision ID: 4d77cbfb54c6
Revises: e335ab45de3a
Create Date: 2022-07-18 07:11:51.538870

"""

# revision identifiers, used by Alembic.
revision = '4d77cbfb54c6'
down_revision = 'e335ab45de3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
